HOOK_W = 4.9;
HOOK_H = 12;
HOOK_H2 = HOOK_H - HOOK_W;
HOOK_GAP_H = 35;
HOOK_DIFF_V = 28;
HOOK_TOLERANCE_H = 0.1;
HOOK_TOLERANCE_V = 0.3;
HOOK_SLOT_SPACING_H = HOOK_W;
HOOK_SLOT_SPACING_V = 3;

BEARING_DIAMETER = 22.4;
BEARING_RADIUS = BEARING_DIAMETER / 2;
BEARING_WIDTH = 6.8;
BEARING_PIN_SLOT_DIAMETER = 8.5;
BEARING_PIN_SLOT_SPACING_DIAMETER = BEARING_PIN_SLOT_DIAMETER + 2;

ARM_HEIGHT = BEARING_PIN_SLOT_SPACING_DIAMETER + 4;

CONNECTOR_HOOK_SIZE = 5;
CONNECTOR_HOOK_SLOT_SIZE = 3;
CONNECTOR_DEPTH = 8;
CONNECTOR_FRONT_FACE_HEIGHT = ARM_HEIGHT;
CONNECTOR_FRONT_FACE_THICKNESS = 3;
CONNECTOR_FRONT_FACE_TOLERANCE = 0.2;

ROLL_BEARING_NOSE_SIZE = 1;
ROLL_WALL_THICKNESS = 2;
ROLL_DIAMETER_OUTER = (BEARING_RADIUS + ROLL_WALL_THICKNESS) * 2;
ROLL_RADIUS_OUTER = ROLL_DIAMETER_OUTER / 2;
ROLL_DIAMETER_INNER = (BEARING_RADIUS - ROLL_BEARING_NOSE_SIZE) * 2;
ROLL_RADIUS_INNER = ROLL_DIAMETER_INNER / 2;
ROLL_FRAME_CUT_LENGTH = 0.5;

PIN_FRAME_CUT_LENGTH = 8;
PIN_DIAMETER = 7.8;
PIN_RADIUS = PIN_DIAMETER / 2;
PIN_CUT_HEIGHT = 1;

PTFE_TUBE_HOLE_DIAMETER = 4.3;
PTFE_TUBE_HOLE_RADIUS = PTFE_TUBE_HOLE_DIAMETER / 2;

LABEL_DEPTH = 0.8;
LABEL_ACTUAL_FONT = LABEL_FONT_CUSTOM != "" ? LABEL_FONT_CUSTOM : LABEL_FONT;

FRAME_HEIGHT = HOOK_W + HOOK_H * HEIGHT_UNITS + HOOK_DIFF_V * (HEIGHT_UNITS - 1)
    + HOOK_TOLERANCE_V * HEIGHT_UNITS + HOOK_SLOT_SPACING_V;
