FRAME_SPOOL_SPACING = 2;
FRAME_INNER_WIDTH = SPOOL_WIDTH + 2 * FRAME_SPOOL_SPACING;

CONNECTOR_TOTAL_LENGTH = 2 * (CONNECTOR_HOOK_SIZE + CONNECTOR_HOOK_SLOT_SIZE) + FRAME_INNER_WIDTH;

ROLL_LENGTH = SPOOL_WIDTH + 2 * FRAME_SPOOL_SPACING + 2 * ROLL_FRAME_CUT_LENGTH;
